{"name": "PoS Store - Validate navigation to New customer page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=93.0.4577.63)\n\n", "trace": "  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/GigaStorePOSSsteps.py\", line 52, in close_browser\n    context.driver.close()\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given login to the GigaStore", "status": "passed", "start": 1631186853228, "stop": 1631186872835}, {"name": "When navigate to Point of Sale store", "status": "passed", "start": 1631186872836, "stop": 1631186876948}, {"name": "And click on New Customer card", "status": "passed", "start": 1631186876949, "stop": 1631186879027}, {"name": "Then verify navigation to New Customer card", "status": "passed", "attachments": [{"name": "screenshot", "source": "6d7c7226-340c-41d3-a87f-a8cd88586767-attachment.png", "type": "image/png"}], "start": 1631186879028, "stop": 1631186879383}, {"name": "And close browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=93.0.4577.63)\n\n", "trace": "  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/GigaStorePOSSsteps.py\", line 52, in close_browser\n    context.driver.close()\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/tehaseenmujawar/PycharmProjects/BDDFirstProject/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1631186879384, "stop": 1631186879389}], "start": 1631186853228, "stop": 1631186879389, "uuid": "1142f3dc-514e-435b-9a7f-e8ba1120ac54", "historyId": "799df3f7d33c05dbef19f8f0fa1c7c58", "fullName": "GigaStore Point of Sale Store: PoS Store - Validate navigation to New customer page", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "GigaStore Point of Sale Store"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}